# Generated by Django 6.0.1 on 2026-05-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit_coruna', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='lugar',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, to='visit_coruna.etiqueta'),
        ),
    ]
